var LevelCodes = {
  'mouse': '01',
  'cat': '02',
  'button': '04',
  'scientist': '05',
  'doors': '06',
  'hidden': '07',
  'escape': '08',
  'hide': '09',
  'run': '0a',
  'shadow': '0b',
  'cycle': '0c',
  'pathfinder': '0d',
  'holes': '0e',
  'friend': '0f',
  'multiple': '10',
  'traps': '11',
  'slow': '12',
  'telsas': '14',
  'gap': '15',
  'gate': '16',
  'maze': '1e',
  'buttons': '1f',
  'endings': '20'
};
